### ISSUE TITLE
Add a noscript fallback img

### ISSUE THREAD

**Issue by user-none** [robwierzbowski/jekyll-picture-tag#102]
I'm using Javascript lazy loading for images by applying a class to the generated <img>. It would be useful to have a config option to generate an img with only the "src" attribute in a <noscript> tag for fallback.

**Comment by rbuchberger** [comment]
I think I get what you're asking for, but could you give me an example of what the output would look like?

**Comment by user-none** [comment]
Here is an example of what I'm suggesting.

```
<img class="lazyload"
  data-src="/...-800by600-89798f.jpg"
  data-srcset="/...-400by300-89798f.jpg 400w" />

<noscript>
  <img src="/...-800by600-89798f.jpg" />
</noscript>
```

The first `<img>` tag is generated by picture-tag and is using `data-*` so the lazy loading JS can add the `src` and `srcset` attributes later. With JS disabled in the browser no images are shown. Adding the additional `<img>` within the `<noscript>` tag will a JS off browser to still load and display the image.

**Comment by rbuchberger** [comment]
I've come up with an [implementation](https://github.com/robwierzbowski/jekyll-picture-tag/tree/noscript-fallback), could you check it out for me? You can test it by pointing your gemfile at that branch:

```
gem 'jekyll-picture-tag', git: 'https://github.com/robwierzbowski/jekyll-picture-tag/', branch: 'noscript-fallback'
```
It will still have classes applied, because I figure CSS is independent of javascript, but it won't have a srcset. We could easily put up anything up to a full `<picture>` tag, sources and all.

**Comment by user-none** [comment]
Working great. I'm seeing the `noscript` tag being added when `markup:` is set to `data_*`.

Oddly I am seeing some strange behavior with markdown files similar to #104. 
This:
```
{% picture s.png %}
```
Gets turned into this:
```
<p><img data-src="/generated/s-800by106-70cbfd.png" data-srcset="/generated/s-200by26-70cbfd.png 200w, /generated/s-400by53-70cbfd.png 400w, /generated/s-800by106-70cbfd.png 800w, /generated/s-1288by170-70cbfd.png 1288w" /></p>
<noscript>
  <img src="/generated/s-800by106-70cbfd.png" />
</noscript>
```
Notice the `<noscript>` is outside of the `<p>`. Also, using a markdown link it gets broken like in #104. It looks like that issue is triggered when j-p-t outputs multiple tags.

**Comment by rbuchberger** [comment]
Yeah, you're right I see that now. Doesn't happen with `<picture>` tags, but does with `<img>` tags. I thought I had an extra line break in the output, but removing it didn't fix it. 

I'll go ahead and merge it in since it's not a new bug and it introduces good functionality, but I really need to figure out how to tell kramdown to keep its hands off my HTML!
