### ISSUE TITLE
Push new gem to rubygems.org (Jekyll 4 Support)

### ISSUE THREAD

**Issue by kylekirkby** [robwierzbowski/jekyll-picture-tag#135]
Hi @robwierzbowski,

:100: for merging my PR earlier! 

Could we potentially push a new version of the gem to rubygems.org? This might be a good opportunity to push the gem under the new _underscored_ name (jekyll_picture_tag).

BR,

Kyle

**Comment by rbuchberger** [comment]
No worries! Rob isn't super busy with this project anymore, I've taken over maintaining it for the most part. 

I'm working on getting it back up on rubygems, but it's a *touch* complicated. I've described all the reasons why in #120 (and the corresponding draft pull request #121)

Since this issue falls entirely under that issue I'm going to close this one as a duplicate. You're right though, this is something that needs to be done and I really should quit procrastinating on it!
