### ISSUE TITLE
Very slow build times

### ISSUE THREAD

**Issue by jameseilers** [robwierzbowski/jekyll-picture-tag#58]
Has anyone had any issues with very slow build times? I'm looking at about 6 seconds with only 1 article (26 images) and with my full site (only around 15 articles) its almost 15 minutes. I've narrowed it down to the picture tag plugin but beyond that I don't know. 

Any ideas?

http://jameseilers.com

**Comment by btobolaski** [comment]
Yes, it has to do with the count of images in your site. See my pull request https://github.com/robwierzbowski/jekyll-picture-tag/pull/55 for how to speed it up

**Comment by stuntbox** [comment]
@btobolaski: Wow, that would be a huge improvement. What would it take to make it happen?

**Comment by jameseilers** [comment]
Excellent solution, its working great.

**Comment by btobolaski** [comment]
I've merge in my pull request, so this should be fixed now.

**Comment by faustgertz** [comment]
Before this improvement, [my site](https://github.com/vesterheim/vesterheim.github.io) took an average of eight and a half minutes to build without generating any new images. Since this improvement, it appears to takes an average of a minute and a quarter to build without generating any new images. Amazing. Thank you!
