### ISSUE TITLE
Add new markup for support of "srcset-w"

### ISSUE THREAD

**Issue by nhoizey** [robwierzbowski/jekyll-picture-tag#68]
Most responsive image needs require only the `srcset-w` attribute on the `<img>` tag, `<picture>` being necessary only for Art Direction:
http://blog.cloudfour.com/dont-use-picture-most-of-the-time/

**Comment by btobolaski** [comment]
That was very enlightening, thank you. So going on that information, this plugin shouldn't generate `<picture>` tags at all, since it just generates a series of resized images. My plan is to add the `srcset` markup option and then depreciate the `picture` markup. 

I have a plan for how I'd like the `srcset` markup option to work and I'll try it out when I get a chance.

**Comment by nhoizey** [comment]
I think `<picture>` is also useful, but only if we can provide several images in our content, which might be difficult, so `srcset-w` should be the default/example configuration, yes.

It's really great to know you have a plan!

**Comment by kyleaffolder** [comment]
Hi @btobolaski — curious if you ever took a stab at adding in `srcset` functionality to this plugin? I couldn't agree more that supporting the picture spec by using `srcset` markup is the best option right now. I started trying to make the switch myself, but sadly I am not much of a Ruby developer. Care sharing any progress you may have made with this, or even what some of your thoughts were regarding plan/setup?
